### ISSUE TITLE
Gnome shell crashes on login when taskbar is enabled

### ISSUE THREAD

**Issue by blackjackshellac** [zpydr/gnome-shell-extension-taskbar#112]
All I know is that when I enable taskbar the shell crashes at login pretty conssitently, and periodically while running.  If i disable it, I don't see any crashes.  This is on Fedora 24 beta with gnome shell 3.20.2.

I'm really not sure what to do, if you have any suggestions about how to debug this I would be happy to help.

**Comment by Larx** [comment]
Same here, openSUSE with Gnome 3.20.1 and 3.20.2. gnome-shell crashes about 50% of all startups when TaskBar is enabled. Killing the X-server with CTRL-ALT-Backspace and re-login helps most of the time.
When there is no crash, the startup is definitely longer with TaskBar enabled (without: almost instantly afer login, with TaskBar: about 15 secs).

**Comment by al-paca** [comment]
I am seeing the same on Arch with Gnome 3.20.2.  I see the issue from time to time when unlocking as well.

It seems to me that it crashes the gnome-shell process everytime.  Sometimes it crashes out to GDM, others it reloads to the desktop.  I have noticed Gnome-shell memory usage spikes on login/unlock.  Sometimes the process will consume upwards of 1.5GB of memory, then crash it crashes back to GDM.  Others, it climbs to 500-600MB, gnome-shell restarts and I get my desktop.

Thinking it could be an extension conflict, I have disabled all others and I still see the issue.

**Comment by blackjackshellac** [comment]
I haven't had a single shell crash since disabling taskbar 10 days ago.  And yes, I had gone through the process of disabling all of my extensions and then enabling them one by one to be sure it was taskbar.  Little doubt now.   Looking glass never shows any errors for the extension so that's no help.  No idea where to look.

**Comment by yevgenyz** [comment]
I suffered from the constant gnome-shell crashes with this extension enabled too.
But IMHO I have found the feature that caused that - disabling "Dash (Overview)" option (it's on by default) caused the failures in my case. Looks like leaving the option enabled keeps gnome-shell running.

**Comment by blackjackshellac** [comment]
I'm not sure what this option is "Dash(Overview)".  It doesn't appear in my installed version (TaskBar 52).

**Comment by yevgenyz** [comment]
I use the same plugin version and gnome-shell-3.20 on Fedora 24.
The option appears on the "Misc" tab of the plugin preferences.

**Comment by blackjackshellac** [comment]
Ah, sorry, I was looking in the Overview tab.  Anyway, I've always left all those Misc options enabled, and still get crashes.

**Comment by Baltix** [comment]
No crashes on Ubuntu 16.04 with GNOME Shell 3.18.4, maybe issue exists only with version 3.20.x ?

**Comment by idelsink** [comment]
I have the same problem on Fedora 24. 
I also tested it with disabling all and enabling one by one. 
With me it seems that the following applications are causing the crashes:

-    "Do Not Disturb Button"
-    "AppKeys"

I tested by disabling all my extension and only enabling those two. And yes, it crashed (and restarted)

I use Fedora 24, GNOME Shell 3.20.4. I can't really say why this is happening. Perhaps the extension developer can say something clever about this?

At this moment I just disabled those two extensions and the successful boot vs crash ratio has certainly gone down quite a bit. I'm not sure if these are the only extensions that are causing this issue, but I hope that this can help in some way. :-)

**Comment by idelsink** [comment]
idk if it has any conflict with an extension tbh.
I did try to catch some usefull logs.

I get the following log from `journal -b`:

```sh
Sep 26 17:16:31 nano org.gnome.Shell.desktop[1692]: (gnome-shell:1692): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x55a8fe47a690' has no handler with id '67699'
Sep 26 17:16:31 nano org.gnome.Shell.desktop[1692]: (gnome-shell:1692): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x55a8fe47a690' has no handler with id '67699'
Sep 26 17:16:31 nano org.gnome.Shell.desktop[1692]: (gnome-shell:1692): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x55a8fe47a690' has no handler with id '67699'
Sep 26 17:16:31 nano org.gnome.Shell.desktop[1692]: (gnome-shell:1692): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x55a8fe47a690' has no handler with id '67699'
Sep 26 17:16:31 nano org.gnome.Shell.desktop[1692]: (gnome-shell:1692): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x55a8fe47a690' has no handler with id '67699'
Sep 26 17:16:31 nano org.gnome.Shell.desktop[1692]: (gnome-shell:1692): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x55a8fe47a690' has no handler with id '67699'
Sep 26 17:16:31 nano org.gnome.Shell.desktop[1692]: (gnome-shell:1692): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x55a8fe47a690' has no handler with id '67699'
Sep 26 17:16:31 nano org.gnome.Shell.desktop[1692]: (gnome-shell:1692): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x55a8fe47a690' has no handler with id '67699'
Sep 26 17:16:31 nano org.gnome.Shell.desktop[1692]: (gnome-shell:1692): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x55a8fe47a690' has no handler with id '67699'
Sep 26 17:16:31 nano org.gnome.Shell.desktop[1692]: (gnome-shell:1692): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x55a8fe47a690' has no handler with id '67699'
Sep 26 17:16:31 nano org.gnome.Shell.desktop[1692]: (gnome-shell:1692): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x55a8fe47a690' has no handler with id '67699'
Sep 26 17:16:31 nano org.gnome.Shell.desktop[1692]: (gnome-shell:1692): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x55a8fe47a690' has no handler with id '67699'
Sep 26 17:16:31 nano audit[1692]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=1692 comm="gnome-shell" exe=
Sep 26 17:16:31 nano org.gnome.Shell.desktop[1692]: (gnome-shell:1692): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x55a8fe47a690' has no handler with id '67699'
Sep 26 17:16:31 nano org.gnome.Shell.desktop[1692]: **
Sep 26 17:16:31 nano org.gnome.Shell.desktop[1692]: St:ERROR:st/st-bin.c:186:st_bin_dispose: assertion failed: (priv->child == NULL)
Sep 26 17:16:31 nano abrt-hook-ccpp[2289]: Process 1692 (gnome-shell) of user 1000 killed by SIGABRT - dumping core
```

And I did ask the great google for some annswers  and found it referenced in some other extension as a bug..
The author said that he got it fixed, so perhaps take a look at that?
The bug from another extension: <https://github.com/Keruspe/GPaste/issues/112>

I hope the author of this extension can give us some insight in this problem?

**Comment by zpydr** [comment]
Could you please test with the latest github push and please let me know the results. Thank you.

**Comment by idelsink** [comment]
I updated it via deleting the old files and replacing them with a downloaded zip copy of the master branch (c34d775235d31c7ab2351fac95127f60b24b54ea). (the <https://extensions.gnome.org/local/> didn't show an update available, idk how that works or where it get's it's data from)

After a first test/reboot, it still crashes.
The following log files was taken via the command `journal -b`:
```
Oct 20 21:02:54 nano org.gnome.Shell.desktop[1705]: (gnome-shell:1705): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x56344dc31e00' has no handler with id '9223372036854775808'
Oct 20 21:02:54 nano org.gnome.Shell.desktop[1705]: Gjs-Message: JS LOG: loading user theme: /home/ingmar/.local/share/themes/Granite-3.4/gnome-shell/gnome-shell.css
Oct 20 21:02:54 nano org.gnome.Shell.desktop[1705]: Gjs-Message: JS LOG: loading user theme: /home/ingmar/.local/share/themes/Granite-3.4/gnome-shell/gnome-shell.css
Oct 20 21:02:54 nano gnome-software-service.desktop[1850]: (gnome-software:1850): Gs-WARNING **: failed to call gs_plugin_add_updates_historical on packagekit-offline: Curl error (6): 
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: Gjs-Message: JS LOG: Disabling Window Is Ready Notification
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: (gnome-shell:1705): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x56344dc31e00' has no handler with id '6170'
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: Gjs-Message: JS LOG: loading user theme: /home/ingmar/.local/share/themes/Granite-3.4/gnome-shell/gnome-shell.css
Oct 20 21:02:55 nano chronyd[928]: Source 2602:ffa1:500::3 replaced with 83.98.201.134
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: (gnome-shell:1705): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: (gnome-shell:1705): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: (gnome-shell:1705): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: (gnome-shell:1705): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the c
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: (gnome-shell:1705): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContaine
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: (gnome-shell:1705): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the c
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: (gnome-shell:1705): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContaine
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: (gnome-shell:1705): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the c
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: (gnome-shell:1705): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContaine
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: (gnome-shell:1705): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x56344e1c7d20' has no handler with id '24594'
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: (gnome-shell:1705): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x56344e1c7d20' has no handler with id '24594'
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: (gnome-shell:1705): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x56344e1c7d20' has no handler with id '24594'
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: **
Oct 20 21:02:55 nano org.gnome.Shell.desktop[1705]: St:ERROR:st/st-bin.c:186:st_bin_dispose: assertion failed: (priv->child == NULL)
Oct 20 21:02:55 nano audit[1705]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=1705 comm="gnome-shell" exe="/usr/bin/gnom
Oct 20 21:02:55 nano abrt-hook-ccpp[2180]: Process 1705 (gnome-shell) of user 1000 killed by SIGABRT - dumping core
Oct 20 21:02:56 nano abrt-hook-ccpp[2180]: Failed to create core_backtrace: dwfl_getthread_frames failed: not a valid ELF file
Oct 20 21:02:56 nano abrt-hook-ccpp[2180]: /var/spool/abrt is 1434543842 bytes (more than 1279MiB), deleting 'ccpp-2016-10-20-20:59:55-2452'
``` 

The funny thing is that I rarely have gnome crashes on my main desktop. So I can't be totally sure about anything until I've tested the ultimate solution, deleting all gnome data from this user and start from scratch. And at this moment I'm not have the time, nor the energy to do that. So unfortunately this is all that I can say at this moment.

**Comment by idelsink** [comment]
Here is some more log spam after a new reboot.
I'm also using [topicons](https://extensions.gnome.org/extension/495/topicons/) extension perhaps the `ShellTrayIcon` warnings are from that extension?
```
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to remove actor of type 'ShellTrayIcon' from group of class 'StButton', but the container is not the actor's
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): Clutter-WARNING **: Attempting to add actor of type 'ShellTrayIcon' to a container of type 'ShellGenericContainer', but the actor has alrea
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x56364b5beab0' has no handler with id '33167'
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x56364b5beab0' has no handler with id '33167'
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x56364b5beab0' has no handler with id '33167'
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x56364b5beab0' has no handler with id '33167'
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x56364b5beab0' has no handler with id '33167'
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: (gnome-shell:1715): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x56364b5beab0' has no handler with id '33167'
Oct 20 21:15:48 nano audit[1715]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=1715 comm="gnome-shell" exe="/usr/bin/gnome-shell" sig=6
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: **
Oct 20 21:15:48 nano org.gnome.Shell.desktop[1715]: St:ERROR:st/st-bin.c:186:st_bin_dispose: assertion failed: (priv->child == NULL)
Oct 20 21:15:48 nano abrt-hook-ccpp[2323]: Process 1715 (gnome-shell) of user 1000 killed by SIGABRT - dumping core
```

**Comment by zpydr** [comment]
Do you have activated the taskbar bottom panel ? Could you reset all settings via the about tab please and test ? Thank you, I do not get error messages like these.

**Comment by idelsink** [comment]
I'm not using the bottom panel (one taskbar is enough :)) and after a complete reset of the settings, it still seems to crash, see log below:
```
Oct 21 08:22:18 nano org.gnome.Shell.desktop[1729]: (gnome-shell:1729): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x564d76860460' has no handler with id '55674'
Oct 21 08:22:18 nano org.gnome.Shell.desktop[1729]: (gnome-shell:1729): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x564d76860460' has no handler with id '55674'
Oct 21 08:22:18 nano org.gnome.Shell.desktop[1729]: (gnome-shell:1729): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x564d76860460' has no handler with id '55674'
Oct 21 08:22:18 nano org.gnome.Shell.desktop[1729]: (gnome-shell:1729): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x564d76860460' has no handler with id '55674'
Oct 21 08:22:18 nano audit[1729]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=1729 comm="gnome-shell" exe="
Oct 21 08:22:18 nano org.gnome.Shell.desktop[1729]: **
Oct 21 08:22:18 nano org.gnome.Shell.desktop[1729]: St:ERROR:st/st-bin.c:186:st_bin_dispose: assertion failed: (priv->child == NULL)
Oct 21 08:22:18 nano abrt-hook-ccpp[2392]: Process 1729 (gnome-shell) of user 1000 killed by SIGABRT - dumping core
```

**Comment by idelsink** [comment]
Small update:

At this moment it seems to be working fine. E.g. Not crashing on login. 
What I did was a complete reset of my personal preferences of gnome.
I did this by logging out of gnome, switching to a terminal and deleting all gnome related folders in my home directory. 
I can't remember the complete list, but if it looks something that's owned by gnome, it probably is.
(folders like `.gnome .gnome2 .gconf .gconfd .metacity .config/gnome-* .config/dconf` etc..)

After this reset, I reinstalled my extension and configured gnome like the way it was. At that moment the only extensions that where still f*cking things up where both the "topicons" extensions. These place the icons from the bottom left to the top right. I just don't use either of those extensions anymore because I couldn't care less anymore at this point.

The real solution for this problem is still unknown. So this isn't really a "fix" of the problem. It's just a workaround of the actual problem. I don't think I can give more information about this problem at this point. I know too little about the extension framework of gnome to really help you out. I'm just a simple Linux user noting more, nothing less. 

I hope more people can use this drastic decision to relieve themselves of this problem.

**Comment by Larx** [comment]
I use the extension again since a few days ago - without any change of my configuration. It works. For me no need to reset any configuration.

**Comment by blackjackshellac** [comment]
There is still a problem when logging in but otherwise the extension seems to be working fine if I turn it off, logout, log back in and turn it on again.  If I leave it on and logout/in it doesn't start, and prevents several other extensions from starting.  I haven't been able to find anything in 'journalctl -f -o short-iso' in the noise of all the gnome-shell clutter assertion messages.  it only seems to cause problems on login, if I re-enable all of the extensions and restart the shell after logging in everything starts as expected.  I've tried disabling certain extensions and then logging out/in and I've had so many differnet results that it's hard to say what exactly is the cause of the problem, but I suspect it is a race in the initial extension startup process in gnome-shell that is the root cause, or some racy condition between extensions.

It might be possible to run a script at startup to automagically re-enable certain extensions with something like,

```
gnome-shell-extension-tool -d 'TaskBar@zpydr'
sleep 1
gnome-shell-extension-tool -e 'TaskBar@zpydr'
```
and any other bizarrely behaving extensions.

For the record, these are the extensions that are installed in ~/.local/share/gnome-shell/extensions/

```
caffeine@patapon.info
dash-to-dock@micxgx.gmail.com
openweather-extension@jenslody.de
Recents@leonardo.bartoli.gmail.com
TaskBar@zpydr
TeaTime@oleid.mescharet.de
```
I seem to have the most trouble with interactions between TaskBar, Recents and TeaTime, but it's hard to say if any one of them is responsible.

**Comment by Larx** [comment]
I was too optimistic - for me TaskBar is also still not working properly, it's the same as with blackjackshellac :-(.

**Comment by blackjackshellac** [comment]
The problem still exists in Fedora 25, although the shell no longer crashes, but the extension doesn't start, and refuses to start in Tweak, and still doesn't emit any errors.  If I leave it disabled, and login again the extension will start in Tweak (or from the command line).  To further complicate matters, one can no longer restart the shell in Wayland with Alt-F2 'r' ... but I digress :)

**Comment by zpydr** [comment]
Fixed in v55

**Comment by ShayMe21** [comment]
Gnome shell still crashes when I try to open the taskBar extension config options.

**Comment by tliron** [comment]
Can you please comment on which commit fixed this, or what you did exactly? I'm facing St.Bin.run_dispose issues with my own extension.
