### ISSUE TITLE
Slow window move on dual screen

### ISSUE THREAD

**Issue by EtreRe** [zpydr/gnome-shell-extension-taskbar#64]
Hello,

With dual a screen when switching a window from a monitor to an other, it is very slow.

And it is slower and slower over time.

**Comment by hashstat** [comment]
I'm also seeing this issue. It takes some time to get to that state, maybe an hour or so.

I also noticed that applications respond slowly to button clicks. It's most noticeable in Thunderbird. After this extension has been active for a while, the message composition window has a delayed reaction when clicking send or cancel.

All this only happens on my system with multiple monitors.

This is one of my "can't live without it" extensions. And you continue to make it even better. It should be one of those included with Gnome, in my opinion. Thanks for all your work and let me know if I can help narrow down the problem.

By the way, I'm using TaskBar version 40 from extensions.gnome.org with gnome-shell 3.14.3 on Arch Linux with proprietary Nvidia 340 driver (although, I experience the same issue with nouveau driver).

**Comment by zpydr** [comment]
This has been solved.

**Comment by hashstat** [comment]
@zpydr Thanks for working on this. I upgraded to version 41 and am still seeing the same issue. Everything starts out fine, but after some time, moving windows between monitors becomes slow and windows open and close slower. Disabling the TaskBar extension fixes the issue.

I am not a Gnome developer, but I am a programmer, so if there is anything I can do to debug the issue, please let me know. Thanks.

**Comment by zpydr** [comment]
I have modified the monitors-changed signal. Please try this update and if possible deactivate other extensions while testing. Thank you.

**Comment by EtreRe** [comment]
@zpydr I'm using version 41 for several hours now and switching a window from a monitor to an other it's slow again.

If you wan't some more information, let me know.

**Comment by EtreRe** [comment]
Oups my bad ! I'm on version 40… Sorry for the confusion.
I use your Ubuntu PPA Repository.

I will install the 41 version.
Sorry again.

**Comment by zpydr** [comment]
Please use this link to download TaskBar with the latest modification from GitHub: https://github.com/zpydr/gnome-shell-extension-taskbar/archive/master.zip (It is the "Download ZIP" Button on the main page). Save the zipfile to /home/YOURUSERNAME/.local/share/gnome-shell/extensions/  Then extract it and rename the new folder gnome-shell-extension-taskbar-master to TaskBar@zpydr (this is case sensitive). Without the renaming the extension won't work. I have already tested the previous versions on multiple screens and did not have any issues (using Arch Linux), so thank you so much for taking your time to test this.

**Comment by zpydr** [comment]
Sorry, I forgot to mention that you will have to restart GNOME Shell after downloading and renaiming the folder: Alt-F2 + r .You might have to activate the extension using GNOME Tweak Tool or via the On/Off-button at https://extensions.gnome.org/extension/584/taskbar/ .You can install GNOME Tweak Tool from Ubuntu's repository with: 
sudo apt-get install gnome-tweak-tool
TakBar in the Ubuntu repository is at version 41, but does not have the latest modification and at the GNOME Shell Extensions website it has not yet been reviewed and is at version 40.

**Comment by hashstat** [comment]
I pulled the latest changes this morning and used them all day after disabling all other extensions and logging out of and then back into Gnome. Still seeing the same kind of behavior. After disabling the taskbar extension and restarting gnome-shell, everything returns to normal. I'm less concerned about the slow movement between monitors than I am about the slow opening and closing of windows.

Is there some way I can capture debug output around your extension? I thought gnome-shell had some built-in logging capabilities. Maybe I'll look into that to see if it can provide some useful information.

**Comment by EtreRe** [comment]
I also have the issue with the latest version (41).
Switching a window from a screen to an other is slow (as you can see in my gif below) and opening and closing windows is also slow. And the slowness increase in time.

![output](https://cloud.githubusercontent.com/assets/1957591/6473075/14cc0f16-c1f7-11e4-86df-b0091fa8d19a.gif)

**Comment by hashstat** [comment]
As time progresses, my journal is filling up with messages from the TaskBar extension:

> Mar 06 11:26:48 hostname gnome-session[880]: (gnome-shell:958): Gjs-WARNING **: JS ERROR: TypeError: app is null
> Mar 06 11:26:48 hostname gnome-session[880]: TaskBar.prototype.addTaskInList@/home/jdoe/.local/share/gnome-shell/extensions/TaskBar@zpydr/extension.js:1658
> Mar 06 11:26:48 hostname gnome-session[880]: TaskBar.prototype.onWindowsListChanged/<@/home/jdoe/.local/share/gnome-shell/extensions/TaskBar@zpydr/extension.js:1560
> Mar 06 11:26:48 hostname gnome-session[880]: TaskBar.prototype.onWindowsListChanged@/home/jdoe/.local/share/gnome-shell/extensions/TaskBar@zpydr/extension.js:1562
> Mar 06 11:26:48 hostname gnome-session[880]: Windows.prototype.buildWindowsList@/home/jdoe/.local/share/gnome-shell/extensions/TaskBar@zpydr/windows.js:123

This will be repeated many times (increases with time) when I open or close windows. They go away for a time after restarting the extension, but the slow window open and close doesn't necessarily go away with a restart. Looking Glass is not picking up any errors.

I hope this helps some. Let me know if there is more I can do.

**Comment by skochxxl** [comment]
I'm having this issue also with version 43 on a multi monitor system.
